name: Build, Test, Analyze, and Deploy ASP.Net Core app to Azure Web App - ahorcadoutnfrro

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Build, Analyze, and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Ajustado a la versión específica de .NET Core 8

      - name: Restore NuGet packages
        run: dotnet restore Ahorcado.sln

      - name: Build the Solution
        run: dotnet build Ahorcado.sln --configuration Release --no-restore

      - name: Run unit tests with coverage
        run: |
          cd ./UnitTests/
          dotnet test --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=cobertura

      - name: Report coverage
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coveragereport

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coveragereport

      - name: Setup JDK 17 for SonarCloud
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup SonarCloud
        run: |
          dotnet tool install --global dotnet-sonarscanner
          export PATH="$PATH:$HOME/.dotnet/tools"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Analyze with SonarCloud
        run: |
          dotnet sonarscanner begin /k:"efernandezcariaga_Ahorcado" /d:sonar.login="$SONAR_TOKEN" /d:sonar.host.url="https://sonarcloud.io" /o:"efernandezcariaga" /d:sonar.inclusions="**/*.cs"
          dotnet build
          dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"

      - name: Run acceptance tests
        run: |
          cd ./Ahorcado.Acceptance_Test/
          dotnet restore
          dotnet build
          dotnet test

      - name: dotnet publish
        run: dotnet publish AhorcadoMVC/AhorcadoMVC.csproj -c Release -o myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ahorcadoutnfrro'
          slot-name: 'Production'
          package: myapp
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F50C00A3CD114E258668AF71A159E57B }}
