name: dotnet package

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'  # Ajustar según la versión específica de .NET Core 8 que estás utilizando
      
      - name: Restore NuGet packages
        run: dotnet restore Ahorcado.sln
      
      - name: Build the Solution
        run: dotnet build Ahorcado.sln --configuration Release  # Ajustar la configuración según tus necesidades

      
